export const LEASE_LIST_DATA_REQUEST = "LEASE_LIST_DATA_REQUEST";
export const LEASE_LIST_DATA_LOADED = "LEASE_LIST_DATA_LOADED";
export const LEASE_LIST_DATA_LOAD_FAILURE = "LEASE_LIST_DATA_LOAD_FAILURE";
export const LEASE_DETAILS_DATA_REQUEST = "LEASE_DETAILS_DATA_REQUEST";
export const LEASE_DETAILS_DATA_LOADED = "LEASE_DETAILS_DATA_LOADED";
export const LEASE_DETAILS_DATA_LOAD_FAILURE = "LEASE_DETAILS_DATA_LOAD_FAILURE";